alias vi='nvim'
alias vim='nvim'
alias df="df -Tha --total"
alias du="du -ach | sort -h"
alias free="free -mt"
alias ps="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias mkdir="mkdir -pv"
alias myip='curl ipinfo.io/ip'
alias ports='netstat -tulanp'
